name: Download file

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          curl -L https://github.com/sinavm/melishekan/releases/download/v1.0/melishekan-nv_01.npv -o melishekan-nv_01.npv
      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: melishekan-nv_01.npv
